const URL_TEST_PROFILE =
    'https://rocketleague.tracker.network/rocket-league/steam/76561197994277769';

const URL_TEST_PEAKS =
    'https://api.tracker.gg/api/v2/rocket-league/standard/profile/steam/76561197994277769/segments/peak-ratings?';

const kanaFields = [
    'Date',
    'Team name',
    'Contact email',
    'Contact Joukkueen nimi',
    'Contact Organisaation nimi',
    'Contact Organisaation Y-tunnus',
    'Contact Kapteenin Discord-nimimerkki',
    'Contact Varakapteenin Discord-nimimerkki',
    'Player 1 name',
    'Player 1 email',
    'Player 1 In-game nimimerkki',
    'Player 1 Nimi',
    'Player 1 Henkilökohtainen työsähköposti',
    'Player 1 Rocket League Tracker -profiili',
    'Player 1 Rank / Tier',
    'Player 1 Varapelaaja',
    'Player 2 name',
    'Player 2 email',
    'Player 2 In-game nimimerkki',
    'Player 2 Nimi',
    'Player 2 Henkilökohtainen työsähköposti',
    'Player 2 Rocket League Tracker -profiili',
    'Player 2 Rank / Tier',
    'Player 2 Varapelaaja',
    'Player 3 name',
    'Player 3 email',
    'Player 3 In-game nimimerkki',
    'Player 3 Nimi',
    'Player 3 Henkilökohtainen työsähköposti',
    'Player 3 Rocket League Tracker -profiili',
    'Player 3 Rank / Tier',
    'Player 3 Varapelaaja',
    'Player 4 name',
    'Player 4 email',
    'Player 4 In-game nimimerkki',
    'Player 4 Nimi',
    'Player 4 Henkilökohtainen työsähköposti',
    'Player 4 Rocket League Tracker -profiili',
    'Player 4 Rank / Tier',
    'Player 4 Varapelaaja',
    'Player 5 name',
    'Player 5 email',
    'Player 5 In-game nimimerkki',
    'Player 5 Nimi',
    'Player 5 Henkilökohtainen työsähköposti',
    'Player 5 Rocket League Tracker -profiili',
    'Player 5 Rank / Tier',
    'Player 5 Varapelaaja'
];
